### ISSUE TITLE
Update to version 0.5.1 to fix BOM table error

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/package-for-kpack#6]
due to the changes in the lifecycle and chainging BOM table config, a release with version 0.5.1 would be great to prevent errors such as:
"ERROR: failed to build: bom table isn't supported in this buildpack api version. The BOM should be written to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>"

**Comment by tomkennedy513** [comment]
https://github.com/vmware-tanzu/community-edition/pull/3228
